
FROM trnielsen/jhub37_mantid_sasview:latest

USER root

RUN apt-get update && apt-get install -y \
            libboost-dev \
            libboost-filesystem-dev \
            libboost-program-options-dev \
            libboost-regex-dev \
            libboost-iostreams-dev \
            libcerf-dev \
            qt5-default  

# Install BornAgain
# As written in https://www.bornagainproject.org/documentation/getting-started/installation/
COPY BornAgain-1.17 /opt/pylib/BornAgain-1.17

# Fix error while loading shared libraries: libQt5Core.so.5
RUN strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so

# default command will launch Jupyter
ENV PYTHONPATH /opt/pylib/BornAgain-1.17:$PYTHONPATH


USER $NB_USER

WORKDIR $HOME
