
FROM trnielsen/jhub37_mcstas_mantid:latest

USER $NB_USER

# Install McStasScript and dependencies
RUN pip install mcstasscript

# Change McStas path
USER root
COPY configuration.yaml  /opt/conda/lib/python3.7/site-packages/mcstasscript

USER $NB_USER
WORKDIR $HOME
