FROM trnielsen/jhub38_dram_aug2021_ds_welcome:latest



USER $NB_USER




#RUN conda install --yes \
#      -c conda-forge \
#      scipp/label/dev::ess \
#      yapf \
#      scipp/label/dev::scippwidgets \
#      sphinx>=1.6 \
#      sphinx_rtd_theme \
#      nbsphinx \
#      psutil \
#      pythreejs && \
#    conda clean -afy

RUN conda install --yes -c conda-forge scipp/label/dev::ess 

WORKDIR $HOME
