FROM trnielsen/jhub38_dram_sep2021_ds:latest



USER $NB_USER



RUN conda install --yes \
      -c conda-forge \
      ess-dmsc::ess-streaming-data-types \
      h5py \
      ipympl \
      ipython \
      ipywidgets \
      jupyterlab \
      jupyterlab_widgets \
      jupyter_nbextensions_configurator \
      matplotlib-base \
      nodejs \
      python-confluent-kafka \
      pythreejs \
      #scipp::mantid-framework \
      scipp::scippneutron \
      scipp/label/dev::mantid-framework \
      #scipp/label/dev::scippneutron \
      scipp/label/dev::ess \
      scipp::scipp && \
    conda clean -afy

# Pip
#RUN pip install ess-streaming-data-types

# Avoid weird tornado AttributeError
#RUN pip install --upgrade nbconvert




#RUN conda update -n base conda --yes

WORKDIR $HOME
