
FROM trnielsen/jhub38_dram_sep2021_ds_mcstas:latest

USER $NB_USER

# Install McStasScript and dependencies
RUN pip install mcstasscript

# Change McStas path
USER root
COPY configuration.yaml  /opt/conda/lib/python3.8/site-packages/mcstasscript

USER $NB_USER
WORKDIR $HOME
